In [1]:
# Importing libraries.
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotInteractableException

In [2]:
# Opening webdriver.
driver = webdriver.Chrome(r"C:\Users\HOMA\Downloads\chromedriver_win32 (1)\chromedriver.exe")

In [3]:
# Url of the website.
url = "https://timesofindia.indiatimes.com/archive/year-2019,month-12.cms"

In [4]:
# Getting url.
driver.get(url)

In [5]:
# Getting Urls of all days.
urls=driver.find_elements_by_xpath("//*[@id='calender']/tbody/tr/td/a")
UR=[]
for i in urls:
    UR.append(i.get_attribute('href'))

In [6]:
# All days url.
UR

['https://timesofindia.indiatimes.com/2019/12/1/archivelist/year-2019,month-12,starttime-43800.cms',
 'https://timesofindia.indiatimes.com/2019/12/2/archivelist/year-2019,month-12,starttime-43801.cms',
 'https://timesofindia.indiatimes.com/2019/12/3/archivelist/year-2019,month-12,starttime-43802.cms',
 'https://timesofindia.indiatimes.com/2019/12/4/archivelist/year-2019,month-12,starttime-43803.cms',
 'https://timesofindia.indiatimes.com/2019/12/5/archivelist/year-2019,month-12,starttime-43804.cms',
 'https://timesofindia.indiatimes.com/2019/12/6/archivelist/year-2019,month-12,starttime-43805.cms',
 'https://timesofindia.indiatimes.com/2019/12/7/archivelist/year-2019,month-12,starttime-43806.cms',
 'https://timesofindia.indiatimes.com/2019/12/8/archivelist/year-2019,month-12,starttime-43807.cms',
 'https://timesofindia.indiatimes.com/2019/12/9/archivelist/year-2019,month-12,starttime-43808.cms',
 'https://timesofindia.indiatimes.com/2019/12/10/archivelist/year-2019,month-12,starttime-43809.cms',
 'https://timesofindia.indiatimes.com/2019/12/11/archivelist/year-2019,month-12,starttime-43810.cms',
 'https://timesofindia.indiatimes.com/2019/12/12/archivelist/year-2019,month-12,starttime-43811.cms',
 'https://timesofindia.indiatimes.com/2019/12/13/archivelist/year-2019,month-12,starttime-43812.cms',
 'https://timesofindia.indiatimes.com/2019/12/14/archivelist/year-2019,month-12,starttime-43813.cms',
 'https://timesofindia.indiatimes.com/2019/12/15/archivelist/year-2019,month-12,starttime-43814.cms',
 'https://timesofindia.indiatimes.com/2019/12/16/archivelist/year-2019,month-12,starttime-43815.cms',
 'https://timesofindia.indiatimes.com/2019/12/17/archivelist/year-2019,month-12,starttime-43816.cms',
 'https://timesofindia.indiatimes.com/2019/12/18/archivelist/year-2019,month-12,starttime-43817.cms',
 'https://timesofindia.indiatimes.com/2019/12/19/archivelist/year-2019,month-12,starttime-43818.cms',
 'https://timesofindia.indiatimes.com/2019/12/20/archivelist/year-2019,month-12,starttime-43819.cms',
 'https://timesofindia.indiatimes.com/2019/12/21/archivelist/year-2019,month-12,starttime-43820.cms',
 'https://timesofindia.indiatimes.com/2019/12/22/archivelist/year-2019,month-12,starttime-43821.cms',
 'https://timesofindia.indiatimes.com/2019/12/23/archivelist/year-2019,month-12,starttime-43822.cms',
 'https://timesofindia.indiatimes.com/2019/12/24/archivelist/year-2019,month-12,starttime-43823.cms',
 'https://timesofindia.indiatimes.com/2019/12/25/archivelist/year-2019,month-12,starttime-43824.cms',
 'https://timesofindia.indiatimes.com/2019/12/26/archivelist/year-2019,month-12,starttime-43825.cms',
 'https://timesofindia.indiatimes.com/2019/12/27/archivelist/year-2019,month-12,starttime-43826.cms',
 'https://timesofindia.indiatimes.com/2019/12/28/archivelist/year-2019,month-12,starttime-43827.cms',
 'https://timesofindia.indiatimes.com/2019/12/29/archivelist/year-2019,month-12,starttime-43828.cms',
 'https://timesofindia.indiatimes.com/2019/12/30/archivelist/year-2019,month-12,starttime-43829.cms',
 'https://timesofindia.indiatimes.com/2019/12/31/archivelist/year-2019,month-12,starttime-43830.cms']

In [7]:
# Scraping data of headline through exception handling for all the urls dates.
Date=[]
Author=[]
Vertical=[]
Headline=[]
Description=[]

for u in UR:
    driver.get(u)
    try:                  #exception handling for nosuchelementexception\n",
        head=driver.find_element_by_xpath("//table[@class='cnt']/tbody/tr[2]/td[1]/div[3]/table/tbody/tr[2]/td[1]/span/a")
        head.click()                                                      
        heading=driver.find_element_by_xpath("//h1[@class='_23498']")
        Headline.append(heading.text)
    except NoSuchElementException   as e:
        Headline.append("null")

In [8]:
# Scraping data of author through exception handling for all the urls dates.
Author=[]
for u in UR:
    driver.get(u) 
    try:                  #exception handling for nosuchelementexception\n",
        head=driver.find_element_by_xpath("//table[@class='cnt']/tbody/tr[2]/td[1]/div[3]/table/tbody/tr[2]/td[1]/span/a")
        head.click()                                                      
        aut=driver.find_element_by_xpath("//a[@class='auth_detail']")
        Author.append(aut.text)
    except NoSuchElementException   as e:
        Author.append("null")

In [9]:
# Checking author.
Author

['null',
 'Thinkal Menon',
 'Prathibha Joy',
 'null',
 'Richa Shukla',
 'null',
 'null',
 'null',
 'Vinay Lokesh',
 'Sandra Marina Fernandes',
 'null',
 'null',
 'Hansy Sanctis',
 'null',
 'null',
 'Sandra Marina Fernandes',
 'V Lakshmi',
 'null',
 'null',
 'Sunayana Suresh',
 'Vinay Lokesh',
 'Nupur Amarnath',
 'null',
 'null',
 'Thinkal Menon',
 'Vinay Lokesh',
 'null',
 'null',
 'null',
 'null',
 'Sharanya CR']

In [10]:
# Scraping data of Date through exception handling for all the urls dates.
Date=[]
for u in UR:
    driver.get(u)
    try:                  #exception handling for nosuchelementexception\n",
        head=driver.find_element_by_xpath("//table[@class='cnt']/tbody/tr[2]/td[1]/div[3]/table/tbody/tr[2]/td[1]/span/a")
        head.click()                                                      
        dat=driver.find_element_by_xpath("//div[@class='_3GNSx']")
        Date.append(dat.text)
    except NoSuchElementException   as e:
        Date.append("null")

In [11]:
# Scraping data of Description through exception handling for all the urls dates.
Description=[]
for u in UR:
    driver.get(u) 
    try:                  #exception handling for nosuchelementexception\n",
        head=driver.find_element_by_xpath("//table[@class='cnt']/tbody/tr[2]/td[1]/div[3]/table/tbody/tr[2]/td[1]/span/a")
        head.click()                                                      
        des=driver.find_element_by_xpath("//*[@id='app']/div/div[3]/div[2]/div[1]/div[2]/div[3]/div[2]/div/text()[1]")
        Description.append(des.text)
    except NoSuchElementException   as e:
        Description.append("null")

In [12]:
# Checking Date.
Date

['null',
 'null',
 'null',
 'THIS STORY IS FROM DECEMBER 4, 2019',
 'null',
 'THIS STORY IS FROM DECEMBER 6, 2019',
 'null',
 'THIS STORY IS FROM DECEMBER 8, 2019',
 'null',
 'null',
 'THIS STORY IS FROM DECEMBER 11, 2019',
 'THIS STORY IS FROM DECEMBER 12, 2019',
 'null',
 'null',
 'THIS STORY IS FROM DECEMBER 15, 2019',
 'null',
 'null',
 'THIS STORY IS FROM DECEMBER 18, 2019',
 'null',
 'null',
 'null',
 'null',
 'null',
 'THIS STORY IS FROM DECEMBER 24, 2019',
 'null',
 'null',
 'null',
 'THIS STORY IS FROM DECEMBER 28, 2019',
 'null',
 'THIS STORY IS FROM DECEMBER 30, 2019',
 'null']

In [13]:
# Checking Description.
Description

['null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null',
 'null']

In [19]:
# Creating DataFrame.
News_classification =pd.DataFrame({"headline":Headline,
                "Date":Date,
                "Author":Author,
                "description":Description})

In [20]:
# Final DataFrame.
News_classification

,headline,Date,Author,description
0,null,null,null,null
1,null,null,Thinkal Menon,null
2,null,null,Prathibha Joy,null
3,DJ Alan Walker gears up to perform in Bengaluru,"THIS STORY IS FROM DECEMBER 4, 2019",null,null
4,null,null,Richa Shukla,null
5,What one can expect at the 24th IFFK,"THIS STORY IS FROM DECEMBER 6, 2019",null,null
6,null,null,null,null
7,"'We never travelled much, but decided to go to...","THIS STORY IS FROM DECEMBER 8, 2019",null,null
8,null,null,Vinay Lokesh,null
9,null,null,Sandra Marina Fernandes,null
10,Ab bus! Bengaluru’s newest resolution to tackl...,"THIS STORY IS FROM DECEMBER 11, 2019",null,null
11,Students get innovative on social media to pro...,"THIS STORY IS FROM DECEMBER 12, 2019",null,null
12,null,null,Hansy Sanctis,null
13,null,null,null,null
14,Senior citizens’ flash mob in city stresses on...,"THIS STORY IS FROM DECEMBER 15, 2019",null,null
15,null,null,Sandra Marina Fernandes,null
16,null,null,V Lakshmi,null
17,"We are happy being single, and content with se...","THIS STORY IS FROM DECEMBER 18, 2019",null,null
18,null,null,null,null
19,null,null,Sunayana Suresh,null
20,null,null,Vinay Lokesh,null
21,null,null,Nupur Amarnath,null
22,null,null,null,null
23,Bengaluru’s Christmas entrepreneurs spread fes...,"THIS STORY IS FROM DECEMBER 24, 2019",null,null
24,null,null,Thinkal Menon,null
25,null,null,Vinay Lokesh,null
26,null,null,null,null
27,Mangalureans are extremely hardworking and the...,"THIS STORY IS FROM DECEMBER 28, 2019",null,null
28,null,null,null,null
29,Artistes and filmmakers unite to support speci...,"THIS STORY IS FROM DECEMBER 30, 2019",null,null
30,null,null,Sharanya CR,null

In [21]:
# Converting to csv format.
News_classification.to_csv('News_classification.csv', index = False)

In [22]:
# Final DataFrame.
News_classification

,headline,Date,Author,description
0,null,null,null,null
1,null,null,Thinkal Menon,null
2,null,null,Prathibha Joy,null
3,DJ Alan Walker gears up to perform in Bengaluru,"THIS STORY IS FROM DECEMBER 4, 2019",null,null
4,null,null,Richa Shukla,null
5,What one can expect at the 24th IFFK,"THIS STORY IS FROM DECEMBER 6, 2019",null,null
6,null,null,null,null
7,"'We never travelled much, but decided to go to...","THIS STORY IS FROM DECEMBER 8, 2019",null,null
8,null,null,Vinay Lokesh,null
9,null,null,Sandra Marina Fernandes,null
10,Ab bus! Bengaluru’s newest resolution to tackl...,"THIS STORY IS FROM DECEMBER 11, 2019",null,null
11,Students get innovative on social media to pro...,"THIS STORY IS FROM DECEMBER 12, 2019",null,null
12,null,null,Hansy Sanctis,null
13,null,null,null,null
14,Senior citizens’ flash mob in city stresses on...,"THIS STORY IS FROM DECEMBER 15, 2019",null,null
15,null,null,Sandra Marina Fernandes,null
16,null,null,V Lakshmi,null
17,"We are happy being single, and content with se...","THIS STORY IS FROM DECEMBER 18, 2019",null,null
18,null,null,null,null
19,null,null,Sunayana Suresh,null
20,null,null,Vinay Lokesh,null
21,null,null,Nupur Amarnath,null
22,null,null,null,null
23,Bengaluru’s Christmas entrepreneurs spread fes...,"THIS STORY IS FROM DECEMBER 24, 2019",null,null
24,null,null,Thinkal Menon,null
25,null,null,Vinay Lokesh,null
26,null,null,null,null
27,Mangalureans are extremely hardworking and the...,"THIS STORY IS FROM DECEMBER 28, 2019",null,null
28,null,null,null,null
29,Artistes and filmmakers unite to support speci...,"THIS STORY IS FROM DECEMBER 30, 2019",null,null
30,null,null,Sharanya CR,null

Thank You..!!